/*For timer*/
export const CHANGE_ACTIVITY = 'CHANGE_ACTIVITY';
export const CHANGE_CLOCK_STATUS = 'CHANGE_CLOCK_STATUS'
export const INCREMENT_TIMER_ITEM = 'INCREMENT_TIMER_ITEM'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_DURATION_HHMMSS = 'SET_DURATION_HHMMSS'
export const SET_IS_WARNING = 'SET_IS_WARNING'
export const SET_START_TIME = 'SET_START_TIME'
export const SET_SHOULD_OPEN_MODAL = 'SET_SHOULD_OPEN_MODAL'
export const TOGGLE_FROM_POMODORRO = 'TOGGLE_FROM_POMODORRO'
export const POMODORRO_PLAYING_COUNT = 'POMODORRO_PLAYING_COUNT'

/*For global*/
export const SET_DATA_FROM_LS = 'SET_DATA_FROM_LS'
/* for settings*/
export const TOGGLE_POMODORRO = 'TOGGLE_POMODORRO'
export const POMODORRO_TIME = 'POMODORRO_TIME'